import { Department } from '@/types'

export const departments: Department[] = [
    {
        id: 'income_tax',
        name: 'Income Tax Department',
        name_hi: 'आयकर विभाग',
        logo: 'income_tax',
        color: 'bg-orange-50 border-orange-200 text-orange-800',
        services: [
            {
                id: 'pan_card',
                name: 'PAN Card Application',
                name_hi: 'पैन कार्ड आवेदन',
                description: 'Complete form + ID proofs. Clubbed PDF.',
                description_hi: 'पूरा फॉर्म + आईडी प्रूफ। संयुक्त पीडीएफ।',
                rules: {
                    maxSizeKB: 2048,
                    minDPI: 200,
                    backgroundColor: '#FFFFFF',
                    orientation: 'portrait',
                    allowedFormats: ['.pdf'],
                    removeShadows: true,
                },
            },
            {
                id: 'pan_photo',
                name: 'PAN Application Photo',
                name_hi: 'पैन आवेदन फोटो',
                description: '3.5x2.5cm photo for PAN application.',
                description_hi: 'पैन आवेदन के लिए 3.5x2.5cm फोटो।',
                rules: {
                    maxSizeKB: 50,
                    minDPI: 200,
                    backgroundColor: '#FFFFFF',
                    orientation: 'portrait',
                    aspectRatio: { width: 25, height: 35 },
                    allowedFormats: ['.jpg', '.jpeg'],
                    removeShadows: true,
                    faceDetection: true,
                },
            },
            {
                id: 'itr_upload',
                name: 'ITR / Statutory Forms',
                name_hi: 'आईटीआर / वैधानिक फॉर्म',
                description: 'General attachments for e-Filing portal.',
                description_hi: 'ई-फाइलिंग पोर्टल के लिए सामान्य अटैचमेंट।',
                rules: {
                    maxSizeKB: 5120,
                    minDPI: 300,
                    orientation: 'portrait',
                    allowedFormats: ['.pdf', '.zip'],
                    removeShadows: false,
                },
            },
        ],
    },
    {
        id: 'uidai',
        name: 'Aadhaar (UIDAI)',
        name_hi: 'आधार (UIDAI)',
        logo: 'aadhaar',
        color: 'bg-yellow-50 border-yellow-200 text-yellow-800',
        services: [
            {
                id: 'aadhaar_update',
                name: 'Identity/Address Proof',
                name_hi: 'पहचान/पता प्रमाण',
                description: 'For online Aadhaar update (PoI/PoA).',
                description_hi: 'ऑनलाइन आधार अपडेट के लिए (PoI/PoA)।',
                rules: {
                    maxSizeKB: 2048,
                    minDPI: 300,
                    backgroundColor: '#FFFFFF',
                    orientation: 'portrait',
                    allowedFormats: ['.pdf', '.jpg', '.jpeg', '.png'],
                    removeShadows: true,
                },
            },
        ],
    },
    {
        id: 'state_services',
        name: 'State Gov Services',
        name_hi: 'राज्य सरकार सेवाएं',
        logo: 'state_services',
        color: 'bg-green-50 border-green-200 text-green-800',
        services: [
            {
                id: 'caste_cert',
                name: 'Caste Certificate',
                name_hi: 'जाति प्रमाण पत्र',
                description: 'MahaOnline/State portal uploads.',
                description_hi: 'महाऑनलाइन/राज्य पोर्टल अपलोड।',
                rules: {
                    maxSizeKB: 256,
                    minDPI: 200,
                    orientation: 'portrait',
                    allowedFormats: ['.jpg', '.jpeg', '.pdf'],
                    removeShadows: true,
                },
            },
            {
                id: 'income_cert',
                name: 'Income Certificate',
                name_hi: 'आय प्रमाण पत्र',
                description: 'Income proof documents.',
                description_hi: 'आय प्रमाण दस्तावेज़।',
                rules: {
                    maxSizeKB: 500,
                    minDPI: 200,
                    orientation: 'portrait',
                    allowedFormats: ['.pdf', '.jpg'],
                    removeShadows: true,
                },
            },
        ],
    },
    {
        id: 'passport_seva',
        name: 'Passport Seva',
        name_hi: 'पासपोर्ट सेवा',
        logo: 'passport',
        color: 'bg-blue-50 border-blue-200 text-blue-800',
        services: [
            {
                id: 'passport_photo',
                name: 'Passport Photo',
                name_hi: 'पासपोर्ट फोटो',
                description: '35x45mm (or 2x2 inch). JPEG Only.',
                description_hi: '35x45mm (या 2x2 इंच)। केवल JPEG।',
                rules: {
                    maxSizeKB: 100,
                    minDPI: 300,
                    backgroundColor: '#FFFFFF',
                    orientation: 'portrait',
                    aspectRatio: { width: 35, height: 45 },
                    allowedFormats: ['.jpg', '.jpeg'],
                    removeShadows: true,
                    faceDetection: true,
                },
            },
            {
                id: 'passport_docs',
                name: 'Supporting Documents',
                name_hi: 'सहायक दस्तावेज़',
                description: 'Address proof, Birth proof, etc.',
                description_hi: 'पता प्रमाण, जन्म प्रमाण, आदि।',
                rules: {
                    maxSizeKB: 500,
                    minDPI: 200,
                    orientation: 'portrait',
                    allowedFormats: ['.pdf'],
                    removeShadows: true,
                },
            },
        ],
    },
    {
        id: 'banking',
        name: 'Bank KYC',
        name_hi: 'बैंक केवाईसी',
        logo: 'banking',
        color: 'bg-indigo-50 border-indigo-200 text-indigo-800',
        services: [
            {
                id: 'kyc_docs',
                name: 'KYC Documents',
                name_hi: 'केवाईसी दस्तावेज़',
                description: 'PAN/Aadhaar/Voter ID for Banks (SBI, HDFC, ICICI).',
                description_hi: 'बैंकों (SBI, HDFC, ICICI) के लिए पैन/आधार/वोटर आईडी।',
                rules: {
                    maxSizeKB: 500,
                    minDPI: 200,
                    backgroundColor: '#FFFFFF',
                    orientation: 'landscape',
                    allowedFormats: ['.pdf', '.jpg', '.jpeg'],
                    removeShadows: true,
                },
            },
            {
                id: 'kyc_signature',
                name: 'Signature',
                name_hi: 'हस्ताक्षर',
                description: 'Cropped signature on white paper.',
                description_hi: 'सफेद कागज पर कटा हुआ हस्ताक्षर।',
                rules: {
                    maxSizeKB: 50,
                    minDPI: 300,
                    backgroundColor: '#FFFFFF',
                    orientation: 'landscape',
                    allowedFormats: ['.jpg', '.jpeg'],
                    removeShadows: true,
                    requireSignature: true,
                },
            },
        ],
    },
    {
        id: 'general_tools',
        name: 'General Tools',
        name_hi: 'सामान्य टूल',
        logo: '🛠️',
        color: 'bg-gray-50 border-gray-200 text-gray-800',
        services: [
            {
                id: 'compress_pdf',
                name: 'Compress PDF',
                name_hi: 'पीडीएफ कंप्रेस करें',
                description: 'Reduce PDF size while maintaining quality.',
                description_hi: 'गुणवत्ता बनाए रखते हुए पीडीएफ का आकार कम करें।',
                rules: {
                    maxSizeKB: 500,
                    minDPI: 150,
                    orientation: 'any',
                    allowedFormats: ['.pdf'],
                    removeShadows: false,
                },
            },
            {
                id: 'compress_image',
                name: 'Compress Image',
                name_hi: 'छवि कंप्रेस करें',
                description: 'Optimize JPG/PNG images for web upload.',
                description_hi: 'वेब अपलोड के लिए JPG/PNG छवियों को अनुकूलित करें।',
                rules: {
                    maxSizeKB: 2048,
                    minDPI: 200,
                    backgroundColor: '#FFFFFF',
                    orientation: 'any',
                    allowedFormats: ['.jpg', '.jpeg', '.png'],
                    removeShadows: false,
                },
            },
            {
                id: 'self_attestation',
                name: 'Self-Attestation Stamper',
                name_hi: 'स्व-सत्यापन स्टैपर',
                description: 'Stamp your signature on all pages of a PDF/Image.',
                description_hi: 'पीडीएफ/इमेज के सभी पेजों पर अपना सिग्नेचर स्टैम्प करें।',
                rules: {
                    maxSizeKB: 5120,
                    minDPI: 300,
                    orientation: 'any',
                    allowedFormats: ['.pdf', '.jpg', '.jpeg', '.png'],
                    removeShadows: false,
                },
            },
            {
                id: 'signature_fixer',
                name: 'Signature Darkener',
                name_hi: 'हस्ताक्षर गहरा करें',
                description: 'Make faint scanned signatures deep black.',
                description_hi: 'धुंधले स्कैन किए गए हस्ताक्षरों को गहरा काला बनाएं।',
                rules: {
                    maxSizeKB: 50,
                    minDPI: 300,
                    orientation: 'landscape',
                    allowedFormats: ['.jpg', '.jpeg', '.png'],
                    removeShadows: false,
                },
            },
            {
                id: 'dpi_fixer',
                name: 'DPI Injector (300/600)',
                name_hi: 'DPI इंजेक्टर (300/600)',
                description: 'Set image metadata to strictly 300 or 600 DPI.',
                description_hi: 'छवि मेटाडेटा को ठीक 300 या 600 DPI पर सेट करें।',
                rules: {
                    maxSizeKB: 2048,
                    minDPI: 300,
                    orientation: 'any',
                    allowedFormats: ['.jpg', '.jpeg', '.png'],
                    removeShadows: false,
                },
            },
            {
                id: 'auto_crop',
                name: 'Auto-Crop & Deskew',
                name_hi: 'ऑटो-क्रॉप और डेस्क्यू',
                description: 'Straighten and crop document photos automatically.',
                description_hi: 'दस्तावेज़ की तस्वीरों को स्वचालित रूप से सीधा और क्रॉप करें।',
                rules: {
                    maxSizeKB: 2048,
                    minDPI: 300,
                    orientation: 'any',
                    allowedFormats: ['.jpg', '.jpeg', '.png'],
                    removeShadows: true,
                },
            },
            {
                id: 'pdf_unlocker',
                name: 'Aadhaar PDF Unlocker',
                name_hi: 'आधार PDF अनलॉकर',
                description: 'Remove password from your Aadhaar PDF file.',
                description_hi: 'अपनी आधार पीडीएफ फाइल से पासवर्ड हटाएं।',
                rules: {
                    maxSizeKB: 5120,
                    minDPI: 150,
                    orientation: 'any',
                    allowedFormats: ['.pdf'],
                    removeShadows: false,
                },
            },
            {
                id: 'aadhaar_masker',
                name: 'Aadhaar Number Masker',
                name_hi: 'आधार नंबर मास्कर',
                description: 'Mask the first 8 digits of your Aadhaar for privacy.',
                description_hi: 'गोपनीयता के लिए अपने आधार के पहले 8 अंक छिपाएं।',
                rules: {
                    maxSizeKB: 2048,
                    minDPI: 300,
                    backgroundColor: '#FFFFFF',
                    orientation: 'any',
                    allowedFormats: ['.jpg', '.jpeg', '.png', '.pdf'],
                    removeShadows: false,
                },
            },
        ],
    },
]

export function getDepartment(id: string) {
    return departments.find(d => d.id === id)
}

export function getService(id: string) {
    for (const dept of departments) {
        const service = dept.services.find(s => s.id === id)
        if (service) return service
    }
    return null
}
